// <auto-generated />
using System;
using LiddellRoch.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiddellRoch.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231202191748_RemovingEspecificacoesField")]
    partial class RemovingEspecificacoesField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiddellRoch.Models.Bicicleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tamanhos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Bicicletas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Cores = "Black,DarkGray,Red",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(762),
                            Descricao = "A nova Big Wheel 7.4 2022 faz parte da linha de bicicletas de alta performance em alumínio da Oggi.\r\nO novo quadro com a geometria mais agressiva e moderna é ideal para quem deseja encarar desafios técnicos maiores, sem perder o rendimento em outras condições do cross-country. Além disso ela conta com cabeamento interno e padrão Boost, seguindo as tendências das grandes marcas importadas. Esse novo padrão possibilita ao ciclista fazer upgrades com componentes de alto padrão disponíveis no mercado.\r\nOs componentes que equipam essa nova versão foram especialmente selecionados, afim de entregar máxima performance em qualquer ocasião além de um visual moderno e agressivo. Conta com sistema de transmissão Shimano SLX de 12 velocidades, suspensão Manitou Machete com trava no guidão e 100 milímetros de curso e cockpit com componentes ITM NH1.",
                            Estoque = 50,
                            MarcaId = 1,
                            Nome = "Big Wheel 7.4 2022",
                            Peso = 12.5,
                            Preco = 10590.00m,
                            Tamanhos = "S,M,L"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Cores = "Gold",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(772),
                            Descricao = "A Agile Squadra XX1 AXS é uma bicicleta hardtail super leve, com desempenho suficiente para correr etapas da Copa do Mundo de MTB. Para isso, ela aposta no quadro e nas rodas de fibra de carbono, nas suspensão Fox 32 Factory Step Cast Kashima, no grupo eletrônico topo de linha e na geometria mais avançada jamais criada pela engenharia da Oggi.\r\n\r\nPeso total de 9.3Kg com novo quadro em carbono Super Light Oggi, rodas DT Swiss XRC 1501 de 1600g em carbono, cubos DT 250 e roda livre Ratchet EXP 36;\r\nGrupo eletrônico SRAM Eagle XX1 AXS 12V, um dos mais leves e modernos do mundo;\r\nSuspensão Fox 32 Factory Step-Cast Kashima 10mm, câmara de ar Float Evol e cartucho FIT 4 com trava no guidão, com excelente leitura de terreno e suporte nas trilhas inclinadas;\r\nCanote retrátil eletrônico SRAM Reverb AXS, pneus Kenda Booster Pro 2.4 e freios Level Ultimate para total controle.",
                            Estoque = 20,
                            MarcaId = 1,
                            Nome = "Agile Squadra XX1 AXS",
                            Peso = 9.3000000000000007,
                            Preco = 44900.00m,
                            Tamanhos = "M,L"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Cores = "DarkGray,DarkRed",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(784),
                            Descricao = "A combinação entre esportividade, rigidez, baixo peso e conforto faz com que a nova Oggi Velloce Disc 2022 tenha um grande desempenho em diversos lugares, graças ao seu novo quadro, proporcionando mais agressividade e aerodinâmica ao ciclista.",
                            Estoque = 30,
                            MarcaId = 1,
                            Nome = "Velloce Disc 2022",
                            Peso = 11.699999999999999,
                            Preco = 3949.00m,
                            Tamanhos = "S,M,L,XL"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Cores = "Black",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(791),
                            Descricao = "Uma pura mountain bike de XC Repleta de atributos de performance que asseguram a vitória e pesando quase nada. Quadro em carbono Hi-MOD BallisTec / Garfo Lefty Ocho Carbon 100mm / conectividade com App Cannondale integrado\r\nCâmbios Shimano XTR 12 velocidades / pedivela HollowGram\r\nJogo de rodas de carbono HollowGram 25 / guidão de carbono Cannondale 1 / canote ENVE.",
                            Estoque = 10,
                            MarcaId = 2,
                            Nome = "F-Si Hi-MOD 1",
                            Peso = 8.9000000000000004,
                            Preco = 75899.00m,
                            Tamanhos = "S,M,L"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Cores = "MediumVioletRed",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(799),
                            Descricao = "Uma pura mountain bike de XC Repleta de atributos de performance que asseguram a vitória e pesando quase nada. Quadro em carbono Hi-MOD BallisTec / Garfo Lefty Ocho Carbon 100mm / conectividade com App Cannondale integrado\r\nCâmbios Shimano XTR 12 velocidades / pedivela HollowGram\r\nJogo de rodas de carbono HollowGram 25 / guidão de carbono Cannondale 1 / canote ENVE.",
                            Estoque = 50,
                            MarcaId = 2,
                            Nome = "Topstone 2",
                            Peso = 13.1,
                            Preco = 14999.00m,
                            Tamanhos = "S,M,L"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            Cores = "Beige,DarkSeaGreen",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(811),
                            Descricao = "Para você, que valoriza a mobilidade urbana e ainda quer aproveitar sua bike para a prática esportiva, a Activ é a bike ideal. Uma bicicleta versátil, prática, segura e de fácil manutenção, que lhe permite ir além dos centros urbanos e descobrir novas sensações.\r\n\r\nA Activ é oferecida em duas cores e vem montada com seu quadro em alumínio leve, transmissão Shimano Altus 27 velocidades, freios a disco hidráulico, pneus 700X38 e uma linda bolsa, especialmente desenvolvida pela Draisiana.",
                            Estoque = 100,
                            MarcaId = 6,
                            Nome = "Active 2023",
                            Peso = 12.0,
                            Preco = 3890.00m,
                            Tamanhos = "XS,S,M,L,XL,XXL"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 7,
                            Cores = "Black",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(817),
                            Descricao = "Penny-farthing, high wheel e ordinary são termos utilizados para descrever um tipo de bicicleta com a roda dianteira de grande dimensão e a traseira pequena. O modelo tornou-se popular depois do boneshaker e antes do desenvolvimento da \"bicicleta segura\", na década de 1880. Foram os primeiros veículos a serem chamados bicicletas.",
                            Estoque = 5,
                            MarcaId = 1,
                            Nome = "Penny-Farthing",
                            Peso = 18.0,
                            Preco = 8000.00m,
                            Tamanhos = "M"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            Cores = "DarkGray",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(823),
                            Descricao = "A Spark RC World Cup é construída com um quadro de carbono HMX de alta qualidade, que combina rigidez e leveza para uma transferência de potência eficiente e ágil nas trilhas. A fibra de carbono HMX da Scott é conhecida por sua natureza leve e excelente rigidez, o que permite a construção de bicicletas com maior transferência de potência e características de manuseio responsivas. Ao utilizar a fibra de carbono HMX, a Scott produz quadros e componentes leves, mas incrivelmente fortes, permitindo que os ciclistas maximizem seu desempenho na estrada ou na trilha.",
                            Estoque = 3,
                            MarcaId = 7,
                            Nome = "Spark RC World Cup Evo",
                            Peso = 10.4,
                            Preco = 114999.00m,
                            Tamanhos = "S,M,L"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 5,
                            Cores = "Black,Green,Yellow",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(833),
                            Descricao = "Passear de bike é algo extremamente prazeroso, seja em um fim de tarde na praça, ciclovia, e a Caloi desenvolveu a bike perfeita para você fazer esses passeios. A Caloi 400 conta com geometria confort, propiciando uma posição de pilotagem ereta e juntamente ao guidão com uma ergonomia mais elevada oferecendo maior conforto ao pedalar. Além do mais o pedivela ficou levemente posicionado mais a frente, garantindo que a pedalada seja mais fácil e agradável. E para movimenta-la a Caloi selecionou um sistema de transmissão Shimano, sinônimo de confiabilidade e resistência com 21 velocidades, para você poder usufruir de sua bike com a total tranquilidade para relaxar.",
                            Estoque = 30,
                            MarcaId = 3,
                            Nome = "400 Comfort",
                            Peso = 13.0,
                            Preco = 1300.00m,
                            Tamanhos = "S,M,L"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            Cores = "Yellow,DarkGray",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(841),
                            Descricao = "A Cattura Pro apresenta um design moderno e robusto, além de trazer tudo o que um praticante mountain bike busca e espera de uma bike dessa categoria. Apresentando uma geometria race, a Cattura é uma bike muito ágil e tem uma resposta excelente nos mais diversos terrenos com seu quadro projetado em full carbon, possuindo ainda excelente rigidez e baixo peso.",
                            Estoque = 20,
                            MarcaId = 1,
                            Nome = "Cattura Pro Carbon GX 2022",
                            Peso = 12.1,
                            Preco = 24799.00m,
                            Tamanhos = "S,M,L"
                        });
                });

            modelBuilder.Entity("LiddellRoch.Models.CarrinhoCompras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BicicletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BicicletaId");

                    b.ToTable("CarrinhoCompras");
                });

            modelBuilder.Entity("LiddellRoch.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(390),
                            Nome = "Mountain Bike",
                            OrdemExibicao = 1
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(406),
                            Nome = "Estrada",
                            OrdemExibicao = 2
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(408),
                            Nome = "Gravel",
                            OrdemExibicao = 3
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(409),
                            Nome = "Elétrica",
                            OrdemExibicao = 4
                        },
                        new
                        {
                            Id = 5,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(410),
                            Nome = "Urbano e Lazer",
                            OrdemExibicao = 5
                        },
                        new
                        {
                            Id = 6,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(411),
                            Nome = "BMX",
                            OrdemExibicao = 6
                        },
                        new
                        {
                            Id = 7,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(412),
                            Nome = "Clássico",
                            OrdemExibicao = 7
                        });
                });

            modelBuilder.Entity("LiddellRoch.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BicicletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BicicletaId");

                    b.ToTable("Componente");
                });

            modelBuilder.Entity("LiddellRoch.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Marechal Floriano",
                            CodigoPostal = "29255-000",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(616),
                            Endereco = "Av Arthur Haese",
                            Estado = "ES",
                            Nome = "Uprise Eventos",
                            Telefone = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Domingos Martins",
                            CodigoPostal = "29260-000",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(618),
                            Endereco = "Tv. Augusto Schwambach",
                            Estado = "ES",
                            Nome = "Agência AJM",
                            Telefone = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Serra",
                            CodigoPostal = "29160-904",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(619),
                            Endereco = "Av. Brg. Eduardo Gomes",
                            Estado = "ES",
                            Nome = "EryZ FuturAI",
                            Telefone = "1029384756"
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "São Paulo",
                            CodigoPostal = "01153-000",
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(621),
                            Endereco = "Av. Violet Hill",
                            Estado = "SP",
                            Nome = "Dani Floricultura",
                            Telefone = "9925266237"
                        });
                });

            modelBuilder.Entity("LiddellRoch.Models.ImagemProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BicicletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BicicletaId");

                    b.ToTable("ImagemProdutos");
                });

            modelBuilder.Entity("LiddellRoch.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteOficial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(576),
                            IconUrl = "\\images\\marcas\\oggi_logo.svg",
                            Nome = "Oggi",
                            PaisOrigem = "Brasil",
                            SiteOficial = "https://oggibikes.com.br/"
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(579),
                            IconUrl = "\\images\\marcas\\cannondale_logo.svg",
                            Nome = "Cannondale",
                            PaisOrigem = "Estados Unidos da América",
                            SiteOficial = "https://www.cannondale.com/pt-br"
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(580),
                            IconUrl = "\\images\\marcas\\caloi_logo.png",
                            Nome = "Caloi",
                            PaisOrigem = "Brasil",
                            SiteOficial = "https://caloi.com/"
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(581),
                            IconUrl = "\\images\\marcas\\specialized_logo.svg",
                            Nome = "Specialized",
                            PaisOrigem = "Estados Unidos da América",
                            SiteOficial = "https://www.specialized.com/br/pt"
                        },
                        new
                        {
                            Id = 5,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(583),
                            IconUrl = "\\images\\marcas\\tsw_logo.svg",
                            Nome = "TSW",
                            PaisOrigem = "África do Sul",
                            SiteOficial = "https://www.tsw.com/"
                        },
                        new
                        {
                            Id = 6,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(584),
                            IconUrl = "\\images\\marcas\\sense_logo.png",
                            Nome = "Sense",
                            PaisOrigem = "Brasil",
                            SiteOficial = "https://sensebike.com.br/"
                        },
                        new
                        {
                            Id = 7,
                            CriadoEm = new DateTime(2023, 12, 2, 16, 17, 48, 164, DateTimeKind.Local).AddTicks(585),
                            IconUrl = "\\images\\marcas\\scott_logo.svg",
                            Nome = "Scott",
                            PaisOrigem = "Suiça",
                            SiteOficial = "https://www.scott-sports.com/br/pt/"
                        });
                });

            modelBuilder.Entity("LiddellRoch.Models.PedidoDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BicicletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BicicletaId");

                    b.HasIndex("PedidoHeaderId");

                    b.ToTable("PedidoDetalhes");
                });

            modelBuilder.Entity("LiddellRoch.Models.PedidoHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimentoPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRastreio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPedido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transportadora")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PedidoHeaders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiddellRoch.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EmpresaId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("LiddellRoch.Models.Bicicleta", b =>
                {
                    b.HasOne("LiddellRoch.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiddellRoch.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("LiddellRoch.Models.CarrinhoCompras", b =>
                {
                    b.HasOne("LiddellRoch.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiddellRoch.Models.Bicicleta", "Bicicleta")
                        .WithMany()
                        .HasForeignKey("BicicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Bicicleta");
                });

            modelBuilder.Entity("LiddellRoch.Models.Componente", b =>
                {
                    b.HasOne("LiddellRoch.Models.Bicicleta", null)
                        .WithMany("Componentes")
                        .HasForeignKey("BicicletaId");
                });

            modelBuilder.Entity("LiddellRoch.Models.ImagemProduto", b =>
                {
                    b.HasOne("LiddellRoch.Models.Bicicleta", "Bicicleta")
                        .WithMany("ImagensProduto")
                        .HasForeignKey("BicicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bicicleta");
                });

            modelBuilder.Entity("LiddellRoch.Models.PedidoDetalhe", b =>
                {
                    b.HasOne("LiddellRoch.Models.Bicicleta", "Bicicleta")
                        .WithMany()
                        .HasForeignKey("BicicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiddellRoch.Models.PedidoHeader", "PedidoHeader")
                        .WithMany()
                        .HasForeignKey("PedidoHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bicicleta");

                    b.Navigation("PedidoHeader");
                });

            modelBuilder.Entity("LiddellRoch.Models.PedidoHeader", b =>
                {
                    b.HasOne("LiddellRoch.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiddellRoch.Models.ApplicationUser", b =>
                {
                    b.HasOne("LiddellRoch.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LiddellRoch.Models.Bicicleta", b =>
                {
                    b.Navigation("Componentes");

                    b.Navigation("ImagensProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
